### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build
### STAGE 2: Run ###
FROM nginx:alpine
COPY dist/Cimrpoc/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
