version: '3'
services:
  #application angular
  cimr-application:
    image: diamef/cimrpoc:latest
    # build:
    #   context: "./"
    #   dockerfile: "Dockerfile" 
    ports: 
      - '7000:7000' # Port mapping
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 7000"
  
