# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cimrpoc
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: cimrpoc
#           servicePort: 80

apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: cimrpoc 
  name: cimrpoc
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: cimrpoc